name: medvezhiy_ugol
description: App for Medvezhiy ugol

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_simple_dependency_injection: ^2.0.0
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  dio: ^5.0.1
  shared_preferences: ^2.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family:  BottomBarIcons
      fonts:
        - asset: fonts/icons/BottomBarIcons.ttf

flutter_intl:
  enabled: true
  main_locale: ru
