name: medvezhiy_ugol
description: App for Medvezhiy ugol

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl_utils: ^2.8.2
  shimmer: ^3.0.0
  another_flushbar: ^1.12.30
  cupertino_icons: ^1.0.2
  flutter_simple_dependency_injection: ^2.0.0
  flutter_bloc: ^8.1.3
  dio: ^5.3.2
  shared_preferences: ^2.0.18
  mask_text_input_formatter: ^2.4.0
  container_tab_indicator: ^0.3.0
  scroll_to_index: ^3.0.1
  flutter_layout_grid: ^2.0.1
  simple_circular_progress_bar: ^1.0.2
  yandex_mapkit: ^3.3.3
  sliding_up_panel: ^2.0.0+1
  cached_network_image: ^3.2.3
  flutter_native_splash: ^2.2.19
  url_launcher: ^6.1.10
  flutter_slidable: ^3.0.0
  barcode_widget: ^2.0.3
  flutter_launcher_icons: ^0.13.1
  barcode: ^2.2.3
  flutter_svg: ^2.0.5
  equatable: ^2.0.5
  webview_flutter: ^4.4.1
  flip_board: ^1.0.0
  geolocator: ^9.0.2
  map_launcher: ^2.5.0+1
  http: ^1.1.0
  flutter_timer_countdown: ^1.0.5
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  external_app_launcher: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/detail_menu_page/
    - assets/images/stock_page/
    - assets/images/detail_stock_page/
    - assets/images/active_order_page/
    - assets/images/map_page/
    - assets/images/home_page/
    - assets/images/delivery_info_page/
    - assets/images/contact_us_page/
    - assets/images/about_app_page/
    - assets/images/more_page/
    - assets/documents/txt/
    - assets/images/

  fonts:
    - family: Unbounded
      fonts:
        - asset: fonts/Unbounded/Unbounded-Black.ttf
          weight: 900
        - asset: fonts/Unbounded/Unbounded-ExtraBold.ttf
          weight: 800
        - asset: fonts/Unbounded/Unbounded-Bold.ttf
          weight: 700
        - asset: fonts/Unbounded/Unbounded-SemiBold.ttf
          weight: 600
        - asset: fonts/Unbounded/Unbounded-Medium.ttf
          weight: 500
        - asset: fonts/Unbounded/Unbounded-Regular.ttf
          weight: 400
        - asset: fonts/Unbounded/Unbounded-Light.ttf
          weight: 300
        - asset: fonts/Unbounded/Unbounded-ExtraLight.ttf
          weight: 200

    - family: BottomBarIcons
      fonts:
        - asset: fonts/icons/BottomBarIcons.ttf
    - family:  MorePageIcons
      fonts:
        - asset: fonts/icons/MorePageIcons.ttf

    - family: SocialIcons
      fonts:
        - asset: fonts/icons/SocialIcons.ttf

    - family: MorePageIcons
      fonts:
        - asset: fonts/icons/MorePageIcons.ttf

    - family: ToggleSwitcherIcons
      fonts:
        - asset: fonts/icons/ToggleSwitcherIcons.ttf

flutter_intl:
  enabled: true
  main_locale: ru

flutter_native_splash:
  color: "#111216"
  image: assets/images/logo_circle.png
  android_12:
    image: assets/images/logo_circle.png
    color: "#111216"
    image_dark: assets/images/splash_screen/an12_splash_img.png
    icon_background_color_dark: "#111216"
  android: true
  ios: true

flutter_icons:
  android: "launcher"
  ios: true
  image_path: "assets/images/app_icon/app_icon.png"
  adaptive_icon_background: "assets/images/app_icon/app_icon.png"