/// Flutter icons BottomBarIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.

import 'package:flutter/widgets.dart';

class BottomBarIcons {
  BottomBarIcons._();

  static const _kFontFam = 'BottomBarIcons';
  static const String? _kFontPkg = null;

  static const IconData main =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stock =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
