/// Flutter icons MorePageIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MorePageIcons
///      fonts:
///       - asset: fonts/MorePageIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MorePageIcons {
  MorePageIcons._();

  static const _kFontFam = 'MorePageIcons';
  static const String? _kFontPkg = null;

  static const IconData car = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
